### ISSUE TITLE
Cannot find out how to configure pattern `some/path/src/something/{src,include}/namespace`

### ISSUE THREAD

**Issue by galou** [derekwyatt/vim-fswitch#29]
I have use the following pattern:
- source files in `src/namespace`
- header files in `include/namespace`

Both directories are in a path where one of the directories is named `src`. How can I configure `b:fswitchlocs` to have `vim-fswtich` work? `b:fswitchlocs=reg:|src|include|` doesn't work because the first `src` is changed, not the last one.

Thanks!

**Comment by wuhangchen** [comment]
+1， How to savle this probleam?

**Comment by galou** [comment]
I don't use fswitch anymore but still have this in my configuration
```vim
autocmd BufEnter *.cpp let b:fswitchdst = 'h,hpp'
autocmd BufEnter *.cpp let b:fswitchlocs = 'reg:|src/\(.*\)/\([^w]\+\)/src|src/\1/\2/include/\2|,reg:|src|include|,reg:|src|include/*|'
```
Hope this helps!
